### PR TITLE
upgrade libsqlite version

### PR DESCRIPTION
**Pull request by Starnox**
Upgrading the version of sqlite. Quite straightforward:
- replaced version number in Makefile.uk
- replaced link with the updated one
- renamed config.h to sqlite_cfg.h as the new version demands

### CODE REVIEW

**Review by StefanJum — COMMENTED** [review]
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by StefanJum — APPROVED** [review]
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by razvand — CHANGES_REQUESTED** [review]
@Starnox, please improve your commit message. And also sign it. See instructions [here](https://unikraft.org/docs/contributing/submitting-changes/#commits).

**Comment by Starnox** [comment]
> @Starnox, please improve your commit message. And also sign it. See instructions [here](https://unikraft.org/docs/contributing/submitting-changes/#commits).

Done!

**Review by razvand — APPROVED** [review]
Thanks, @Starnox.

Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
